# Generated by Django 4.2.4 on 2023-10-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lti_toolbox", "0002_lticonsumer_url"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lticonsumer",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ltipassport",
            table=None,
        ),
    ]
